/*
 * This file is generated by jOOQ.
 */
package com.singerdream.textdetection.tables.records;


import com.singerdream.textdetection.tables.SensitiveWord;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SensitiveWordRecord extends UpdatableRecordImpl<SensitiveWordRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sensitive_word.id</code>.
     */
    public SensitiveWordRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sensitive_word.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sensitive_word.content</code>.
     */
    public SensitiveWordRecord setContent(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sensitive_word.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SensitiveWord.SENSITIVE_WORD.ID;
    }

    @Override
    public Field<String> field2() {
        return SensitiveWord.SENSITIVE_WORD.CONTENT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public SensitiveWordRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SensitiveWordRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public SensitiveWordRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SensitiveWordRecord
     */
    public SensitiveWordRecord() {
        super(SensitiveWord.SENSITIVE_WORD);
    }

    /**
     * Create a detached, initialised SensitiveWordRecord
     */
    public SensitiveWordRecord(Long id, String content) {
        super(SensitiveWord.SENSITIVE_WORD);

        setId(id);
        setContent(content);
    }
}
