/*
 * This file is generated by jOOQ.
 */
package com.singerdream.comment.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        content;
    private Long          publisherId;
    private Boolean       active;
    private LocalDateTime createdAt;
    private Long          pid;
    private Long          targetId;
    private String        targetSource;

    public Comment() {}

    public Comment(Comment value) {
        this.id = value.id;
        this.content = value.content;
        this.publisherId = value.publisherId;
        this.active = value.active;
        this.createdAt = value.createdAt;
        this.pid = value.pid;
        this.targetId = value.targetId;
        this.targetSource = value.targetSource;
    }

    public Comment(
        Long          id,
        String        content,
        Long          publisherId,
        Boolean       active,
        LocalDateTime createdAt,
        Long          pid,
        Long          targetId,
        String        targetSource
    ) {
        this.id = id;
        this.content = content;
        this.publisherId = publisherId;
        this.active = active;
        this.createdAt = createdAt;
        this.pid = pid;
        this.targetId = targetId;
        this.targetSource = targetSource;
    }

    /**
     * Getter for <code>public.comment.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.comment.id</code>.
     */
    public Comment setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.comment.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>public.comment.content</code>.
     */
    public Comment setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Getter for <code>public.comment.publisher_id</code>.
     */
    public Long getPublisherId() {
        return this.publisherId;
    }

    /**
     * Setter for <code>public.comment.publisher_id</code>.
     */
    public Comment setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
        return this;
    }

    /**
     * Getter for <code>public.comment.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>public.comment.active</code>.
     */
    public Comment setActive(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>public.comment.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.comment.created_at</code>.
     */
    public Comment setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.comment.pid</code>.
     */
    public Long getPid() {
        return this.pid;
    }

    /**
     * Setter for <code>public.comment.pid</code>.
     */
    public Comment setPid(Long pid) {
        this.pid = pid;
        return this;
    }

    /**
     * Getter for <code>public.comment.target_id</code>.
     */
    public Long getTargetId() {
        return this.targetId;
    }

    /**
     * Setter for <code>public.comment.target_id</code>.
     */
    public Comment setTargetId(Long targetId) {
        this.targetId = targetId;
        return this;
    }

    /**
     * Getter for <code>public.comment.target_source</code>.
     */
    public String getTargetSource() {
        return this.targetSource;
    }

    /**
     * Setter for <code>public.comment.target_source</code>.
     */
    public Comment setTargetSource(String targetSource) {
        this.targetSource = targetSource;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(publisherId);
        sb.append(", ").append(active);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(pid);
        sb.append(", ").append(targetId);
        sb.append(", ").append(targetSource);

        sb.append(")");
        return sb.toString();
    }
}
