/*
 * This file is generated by jOOQ.
 */
package com.singerdream.textdetection;


import com.singerdream.textdetection.tables.FlywaySchemaHistory;
import com.singerdream.textdetection.tables.SensitiveWord;
import com.singerdream.textdetection.tables.Tag;
import com.singerdream.textdetection.tables.records.FlywaySchemaHistoryRecord;
import com.singerdream.textdetection.tables.records.SensitiveWordRecord;
import com.singerdream.textdetection.tables.records.TagRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<SensitiveWordRecord> SENSITIVE_WORD_PKEY = Internal.createUniqueKey(SensitiveWord.SENSITIVE_WORD, DSL.name("sensitive_word_pkey"), new TableField[] { SensitiveWord.SENSITIVE_WORD.ID }, true);
    public static final UniqueKey<TagRecord> TAG_PKEY = Internal.createUniqueKey(Tag.TAG, DSL.name("tag_pkey"), new TableField[] { Tag.TAG.ID }, true);
}
