/*
 * This file is generated by jOOQ.
 */
package com.singerdream.textdetection;


import com.singerdream.textdetection.tables.FlywaySchemaHistory;
import com.singerdream.textdetection.tables.SensitiveWord;
import com.singerdream.textdetection.tables.Tag;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.sensitive_word</code>.
     */
    public static final SensitiveWord SENSITIVE_WORD = SensitiveWord.SENSITIVE_WORD;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;
}
