/*
 * This file is generated by jOOQ.
 */
package com.singerdream.textdetection.tables.daos;


import com.singerdream.textdetection.tables.Tag;
import com.singerdream.textdetection.tables.records.TagRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TagDao extends DAOImpl<TagRecord, com.singerdream.textdetection.tables.pojos.Tag, Long> {

    /**
     * Create a new TagDao without any configuration
     */
    public TagDao() {
        super(Tag.TAG, com.singerdream.textdetection.tables.pojos.Tag.class);
    }

    /**
     * Create a new TagDao with an attached configuration
     */
    @Autowired
    public TagDao(Configuration configuration) {
        super(Tag.TAG, com.singerdream.textdetection.tables.pojos.Tag.class, configuration);
    }

    @Override
    public Long getId(com.singerdream.textdetection.tables.pojos.Tag object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.singerdream.textdetection.tables.pojos.Tag> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Tag.TAG.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.singerdream.textdetection.tables.pojos.Tag> fetchById(Long... values) {
        return fetch(Tag.TAG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.singerdream.textdetection.tables.pojos.Tag fetchOneById(Long value) {
        return fetchOne(Tag.TAG.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.singerdream.textdetection.tables.pojos.Tag> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tag.TAG.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.singerdream.textdetection.tables.pojos.Tag> fetchByName(String... values) {
        return fetch(Tag.TAG.NAME, values);
    }
}
